language: csharp
mono: none
dotnet: 2.1.700
install:
  - dotnet restore src/GlobalX.ChatBots.MicrosoftTeams.sln
  - dotnet build src/GlobalX.ChatBots.MicrosoftTeams/GlobalX.ChatBots.MicrosoftTeams.csproj
jobs:
  include:
    - stage: test
      script: dotnet test src/GlobalX.ChatBots.MicrosoftTeams.Tests/GlobalX.ChatBots.MicrosoftTeams.Tests.csproj
    - stage: deploy
      skip_cleanup: true
      provider: script
      script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
      if: branch = master
    - stage: cover
      provider: script
      script: chmod +x ./cover.sh && ./cover.sh
